language: node_js
node_js:
- '0.10'
after_success:
- gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: MBTEIsl/6LlTz6F4PCgBxYUtKt9w1adIYmLRRfebVJN0RvBHjhOv0CpuZTBz/2h6a1+q3yMIqJz5l7wACVMxW9SaC1pvtCj0q0IjW+M3EUvoz8+DHfckC4JvTuf7msFzkiRnW7ivB+z65u0tOSvjT0eYPacRVNVEeXIsevrKWME=
  on:
    tags: true
    repo: Brightspace/peanut-gallery
