language: node_js
node_js:
  - '0.10'
after_success:
  - gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 15fc......c033
    secure: Z7eTZNrxzcMJM2UgVghKA/7xVIRg9mFjckHqeFwg209hT3+LAEDaYkxBPNTeyV/tO96R/BTTMFSXiDbLhbSID1cFwZvW9zL23ZkvS90Yw/m2WDUnVAJ5ZJ6qG9CT6MtwjMa8ZREZlzL7ambBW9FgYl9w9NVi/VjiVLt6b6VkuFA=
  on:
    tags: true
    repo: Brightspace/peanut-gallery
